#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Number of cores
N=${1:-1}

./Allclean

runApplication blockMesh

runApplication simpleFoam

latestTime=$(foamListTimes -latestTime | tail -1)
cp -r 0/C* $latestTime/
sed -i "s/nNonOrthogonalCorrectors[[:space:]]*2;/nNonOrthogonalCorrectors\t\t\t0;/g" system/fvSolution

runApplication reactiveTransportFoam